services:
  web:
    build: .
    container_name: flask_web_app
    expose:
      - "5000"
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
